heat_template_version: 2018-03-02
parameters:
  ext-network:
    type: string
    label: External Network Name
    description: The name of the external network to bridge network to
resources:
  cluster-ext-route:
    type: OS::Neutron::Router
    depends_on: cluster-dmz
    properties:
      name: cluster-ext-route
      external_gateway_info:
        network: { get_param: ext-network }

  cluster-ext-route-iface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: cluster-ext-route }
      subnet: { get_resource: cluster-dmz }

  cluster:
    type: OS::Neutron::Net
    properties:
      name: cluster

  cluster-dmz:
    type: OS::Neutron::Subnet
    properties:
      name: cluster-dmz
      network: { get_resource: cluster }
      cidr: "10.110.0.0/24"
      ip_version: 4

  cluster-pri1:
    type: OS::Neutron::Subnet
    properties:
      name: cluster-pri1
      network: { get_resource: cluster }
      cidr: "10.110.1.0/24"
      gateway_ip: null
      ip_version: 4
      host_routes: 
        - destination: 10.110.0.0/24
          nexthop: 10.110.1.200

  cluster-dmz-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: cluster-dmz-sg
      rules:
        - direction: ingress
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: 213.83.69.6/32
        - direction: ingress
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: 34.240.100.113/32
        - direction: ingress
          port_range_min: 2005
          port_range_max: 2005
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0

  cluster-pri-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: cluster-pri-sg
